spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/radar
    username: radar_user
    password: radar_pass
    driver-class-name: org.postgresql.Driver

  # Hibernate is disabled because Flyway will manage schema.
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  
  # Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration
    



