spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/radar
    username: admin
    password: 12345
    driver-class-name: org.postgresql.Driver

  # Hibernate is disabled because Flyway will manage schema.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
  # Flyway
  flyway:
    enabled: false
    locations: classpath:db/migration
    