spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/radar
    username: radar_user
    password: radar_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

